name: dorminic_co
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  iconsax: ^0.0.8
  intl: ^0.19.0
  logger: ^2.1.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/onboard/
    #- assets/fonts/
    - assets/icons/
    #- assets/videos/

  uses-material-design: true

flutter_icons:
  image_path: "assets/icons/App-icon.png"
  android: true
  ios: true
